<?php

$order_items = [
    [
        "cart_id" => 1,
        "product_id" => 1,
        "product_code" => "PRD-BEV-000001",
        "quantity" => 10,
        "product_name" => "Coca-Cola 1L",
        "description" => "Coca-Cola Original Taste Carbonated Soft Drink",
        "image_url" => "/assets/images/products/cocacola2.jpeg",
        "discount" => 5,
        "promotion_label" => "5% OFF",
        "category" => "Beverages",
        "unit_price" => "Rs. 300.00",
        "discount_amount" => "Rs. 150.00",
        "line_total" => "Rs. 2,850.00",
    ],
    [
        "cart_id" => 1,
        "product_id" => 2,
        "product_code" => "PRD-GNF-000001",
        "quantity" => 7,
        "product_name" => "Nestomalt 400G",
        "description" => "Nestomalt Malted Food Drink Packet 400G",
        "image_url" => "/assets/images/products/nestomalt.jpg",
        "discount" => 0,
        "promotion_label" => "",
        "category" => "Grocery & Food Items",
        "unit_price" => "Rs. 750.00",
        "discount_amount" => "Rs. 0.00",
        "line_total" => "Rs. 5,250.00",
    ],
    [
        "cart_id" => 1,
        "product_id" => 2,
        "product_code" => "PRD-HCP-000001",
        "quantity" => 5,
        "product_name" => "Harpic Fresh 500ml",
        "description" => "Harpic Fresh Floral 500ml",
        "image_url" => "/assets/images/products/harpic.jpg",
        "discount" => 0,
        "promotion_label" => "",
        "category" => "Home Cleaning Products",
        "unit_price" => "Rs. 380.50",
        "discount_amount" => "Rs. 0.00",
        "line_total" => "Rs. 1,902.50",
    ]
    ,
    [
        "cart_id" => 1,
        "product_id" => 2,
        "product_code" => "PRD-HHE-000001",
        "quantity" => 5,
        "product_name" => "Sunlight Detergent Powder - 1kg",
        "description" => "Sunlight Clean and Jasmine Fresh Detergent Powder - 1kg",
        "image_url" => "/assets/images/products/sunlight.jpg",
        "discount" => 10,
        "promotion_label" => "10% OFF",
        "category" => "Household Essentials",
        "unit_price" => "Rs. 320.50",
        "discount_amount" => "Rs. 160.25",
        "line_total" => "Rs. 1,442.25",
    ]
    ,
    [
        "cart_id" => 1,
        "product_id" => 2,
        "product_code" => "PRD-PSC-000001",
        "quantity" => 10,
        "product_name" => "Clogard Toothpaste 200g",
        "description" => "Clogard Toothpaste Natural Salt 200g",
        "image_url" => "/assets/images/products/clogard.jpg",
        "discount" => 0,
        "promotion_label" => "",
        "category" => "Personal Care",
        "unit_price" => "Rs. 360.00",
        "discount_amount" => "Rs. 0.00",
        "line_total" => "Rs. 3,600.00",
    ]
];

$customer_order_info1 = [
    "order_number" => "#ORD-RDCS-260213-1025",
    "order_date" => "13 Feb 2026",
    "customer_name" => "Vijaya Stores - Galle",
    "sales_ref" => "N/A",
    "total_amount" => "Rs. 18,751.46",
    "estimated_delivery_date" => "15 Feb 2026",
    "last_updated" => "13 Feb 2026",
    "order_status" => "Pending",
];
?>