<?php

$retail_products = [
    [
        "product_id" => 1,
        "product_code" => "PRD-BEV-000001",
        "product_name" => "Coca-Cola 1L",
        "promotion" => "-5% OFF FOR 5",
        "category" => "Beverages",
        "unit_price" => 300.00,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/cocacola2.jpeg",
        "is_active" => 1,
        "description" => "Coca-Cola Original Taste Carbonated Soft Drink",
        "rating" => 4.4,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 2,
        "product_code" => "PRD-GNF-000001",
        "product_name" => "Nestomalt 400G",
        "promotion" => "",
        "category" => "Grocery & Food Items",
        "unit_price" => 750.00,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/nestomalt.jpg",
        "is_active" => 1,
        "description" => "Nestomalt Malted Food Drink Packet 400G",
        "rating" => 4.5,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 3,
        "product_code" => "PRD-HCP-000001",
        "product_name" => "Harpic Fresh 500ml",
        "promotion" => "",
        "category" => "Home Cleaning Products",
        "unit_price" => 380.50,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/harpic.jpg",
        "is_active" => 1,
        "description" => "Harpic Fresh Floral 500ml",
        "rating" => 4.1,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 4,
        "product_code" => "PRD-HHE-000001",
        "product_name" => "Sunlight Detergent Powder - 1kg",
        "promotion" => "10% OFF FOR 2",
        "category" => "Household Essentials",
        "unit_price" => 320.50,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/sunlight.jpg",
        "is_active" => 1,
        "description" => "Sunlight Clean and Jasmine Fresh Detergent Powder - 1kg",
        "rating" => 4.2,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 5,
        "product_code" => "PRD-HLP-000001",
        "product_name" => "Strepsils 24S",
        "promotion" => "",
        "category" => "Health Care Products",
        "unit_price" => 650.50,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/strepsils.jpg",
        "is_active" => 1,
        "description" => "Strepsils Honey & Lemon 24S",
        "rating" => 4.6,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "Low Stock"
    ]
    ,
    [
        "product_id" => 6,
        "product_code" => "PRD-PSC-000001",
        "product_name" => "Clogard Toothpaste 200g",
        "promotion" => "",
        "category" => "Personal Care",
        "unit_price" => 360.00,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/clogard.jpg",
        "is_active" => 1,
        "description" => "Clogard Toothpaste Natural Salt 200g",
        "rating" => 4.8,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 7,
        "product_code" => "PRD-BSC-000001",
        "product_name" => "Nature's Secrets Face Wash",
        "promotion" => "%5 OFF FOR 5",
        "category" => "Beauty & Skincare",
        "unit_price" => 370.00,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/ns-fw.jpg",
        "is_active" => 1,
        "description" => "Nature's Secrets Face Wash Carrot 100Ml",
        "rating" => 4.3,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "In Stock"
    ],
    [
        "product_id" => 8,
        "product_code" => "PRD-BCP-000001",
        "product_name" => "Baby Cheramy Baby Talc",
        "promotion" => "",
        "category" => "Baby Care Products",
        "unit_price" => 330.00,
        "minimum_stock_level" => 100,
        "image_url" => "/assets/images/products/bcbt.jpg",
        "is_active" => 1,
        "description" => "Baby Cheramy Baby Talc Classic 100g",
        "rating" => 4.7,
        "created_at" => "2026-02-11 12:20:52",
        "updated_at" => "2026-02-11 12:20:52",
        "available_quantity" => 500,
        "availability" => "Out of Stock"
    ]
];

?>